default.host: http://39.108.103.2:10002/project/api/project
default.ones-check-id: 7FccMcVf
default.ones-check-point: team
default.ones-plugin-id: built_in_apis
default.organization_uuid: 4FmUcdiR
default.team_uuid: 7FccMcVf
default.token: cMCjw1VsQDlQ3PPt7udjU6f0m4NbDoToFrxth76IVSOkjHyn0uDqX19Xcnyo5Pi0
default.user_uuid: UjijyYUY
