default.host: http://120.76.45.123/project/api/project
default.ones-check-id: 6eKY74St
default.ones-check-point: team
default.ones-plugin-id: built_in_apis
default.organization_uuid: 5N6W3noj
default.team_uuid: 6eKY74St
default.token: 6cabYg1IwwTSpE5njCgL9a6wHLZQUbQ2SBjpwG40D70zDjZnkOqmp1R61HyaKujF
default.user_uuid: SMS8ciyv
